---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: generator
  name: generator
  namespace: flux-system
spec:
  template:
    metadata:
      labels:
        app: generator
    spec:
      serviceAccountName: kustomize-controller # edit
      containers:
        - image: ghcr.io/maxgio92/proxy-kubeconfig-generator:0.1.3
          args:
            - --serviceaccount=gitops-reconciler
            - --namespace=dev-team
            - --server=https://capsule-proxy.flux-system.svc:9001
            - --server-tls-secret-name=capsule-proxy
            - --server-tls-secret-namespace=flux-system
          imagePullPolicy: IfNotPresent
          name: generator
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: "RuntimeDefault"
            capabilities:
              drop:
              - ALL
      restartPolicy: OnFailure
