apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: capsule-proxy
  namespace: flux-system
spec:
  serviceAccountName: helm-controller
  releaseName: capsule-proxy
  chart:
    spec:
      chart: capsule-proxy
      sourceRef:
        kind: HelmRepository
        name: clastix
      version: 0.4.6
  values:
    options:
      logLevel: "10"
  interval: 1m
